<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Operations;

use OpenAPI\OpenAPI\Models\Components;
use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class CreateDiscussionRequest
{
    /**
     * The owner of the repository.
     *
     * @var string $owner
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=owner')]
    public string $owner;

    /**
     * The name of the repository.
     *
     * @var string $repo
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=repo')]
    public string $repo;

    /**
     *
     * @var Components\Discussion $discussion
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\Discussion $discussion;

    /**
     * @param  string  $owner
     * @param  string  $repo
     * @param  Components\Discussion  $discussion
     */
    public function __construct(string $owner, string $repo, Components\Discussion $discussion)
    {
        $this->owner = $owner;
        $this->repo = $repo;
        $this->discussion = $discussion;
    }
}