<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


/** Error - Error response */
class Error
{
    /**
     *
     * @var ?string $message
     */
    #[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     *
     * @var ?int $code
     */
    #[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $code = null;

    /**
     * @param  ?string  $message
     * @param  ?int  $code
     */
    public function __construct(?string $message = null, ?int $code = null)
    {
        $this->message = $message;
        $this->code = $code;
    }
}