<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $personalToken
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public string $personalToken;

    /**
     * @param  string  $personalToken
     */
    public function __construct(string $personalToken)
    {
        $this->personalToken = $personalToken;
    }
}